### ISSUE TITLE
Create issues for name-renaming feature

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede#12]
- ganomede-tagizer
  - [x] add parseTag middleware
  - [x] add username-to-name
  - [x] add tag-to-username
- ganomede-events
  - [ ] deploy redis
  - [ ] deploy service
  - [x] create small cli tool to listen for a given channel
  - [x] add `after=latest`
- ganomede-users
  - [ ] deploy
- ganomede-invitations
  - [ ] invite by tag
  - [ ] translate list of invitations
  - [ ] redeploy ganomede invitations
- ganomede-admin
  - [ ] display `name`
  - [ ] search users by `tag`
  - [ ] deploy
- ganomede-challenges
  - [ ] client display `name`
  - [ ] deploy
- ganomede-chat
  - [ ] client display `name`
- ganomede-coordinator
  - [ ] client translate opponents username
- ganomede-notifications
  - [ ] send message by tag
  - [ ] receive message by name
- ganomede-statistics
  - [ ] player rank by tag
  - [ ] player stats by tag
  - [ ] player archives by tag
- ganomede-turngame
  - [ ] send notifications by name

**Comment by elmigranto** [comment]
What's `username`? Is it the same as `userId`?

If yes, why do we want to be able to change it? In case he forgets login, we can allow using email for that. Or any alias in fact (well, maybe only private ones).

If not, which one is used for login and identifying users in our services. 

Or is it how user would like his name to be displayed to other players? Would it be easier to add new alias for that?

**Comment by j3k0** [comment]
> What's `username`? Is it the same as `userId`?

Sorry, I meant the `name` alias. It's what the final user will see as his username.

> If yes, [...] 
> If not, which one is used for login and identifying users in our services. 

We can now use the `tag` (which is a typo-proof version of the `name`). It happens to equal `username` (`userId`) when the user is first created, so wherever we can use a `tag`, the `userId` can be sent as well... or even `name` (the non-type-proof `name`).

> Or is it how user would like his name to be displayed to other players? Would it be easier to add new alias for that?

That's the `name` alias.

I should add a paragraph about all of this in the ganomede-users README.

---

It's already in place in the users module: https://github.com/j3k0/ganomede-users/pull/26

Plan is to allow this to all modules, ganomede-tagizer will be a small lib to make it easier. (with `bodyTag` and `parseTag` middlewares like here https://github.com/j3k0/ganomede-users/blob/35f5caf9921062b3a2cc3b891886242d6b3ee751/src/users-api.coffee#L505-L510)

**Comment by j3k0** [comment]
Reasoning:

 - you registered with username: `LIl0O`
 - want to login again? any of `liloo`, `Li100`, etc. will be accepted
 - someone want to invite you? same thing (no wondering "is it a 0 or a O")
 - you change you `name` to `bilbo`
 - people can still invite you for a game using either of `bilbo` or `lilloo` (no need to know you changed your `name`), you can still login using both...

**Comment by j3k0** [comment]
All modules will now have a dependency over `ganomede-directory`, for tag-to-username translations... so while doing this, it might be an opportunity to also remove the `ganomede-*` &rArr; `redis_authdb` dependency: because eventually we want `ganomede-directory` to be in charge of token validation.
